-- ==============================================================================
-- PURPOSE: Magnitude analysis
-- ==============================================================================

------ Mangnitude analysis ----------

--# Find total numbers of customers bu countries?

    select 
    country,
    count(customer_key)
    from gold.dim_customer
    group by country
    order by count(customer_key) desc


--# Find total numbers of customers bu Gender?

    
    select 
    gender,
    count(customer_key)
    from gold.dim_customer
    group by gender
    order by count(customer_key) desc

--# Find total products by category?

select 
category,
count(product_key)
from gold.dim_products
group by category
order by count(product_key) desc

--# Find average costs in each category ?

select
category, dp.product_key
from gold.dim_products dp 
inner join gold.fact_sales fs
on dp.product_key = fs.product_key

--
select
category,
round(avg(cost)) avg_cost
from gold.dim_products
group by category
order by avg(cost) desc

--# Find the total revenue by the category ?

select

p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f 
left join gold.dim_products p 
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

--# What is the total revenue generated by each customer ?

select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue 
from gold.fact_sales f 
left join gold.dim_customer c  
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by sum(f.sales_amount) desc


--# What is the distribution of sold items across countries ?


select
c.country,
sum(f.sales_amount) as total_revenue 
from gold.fact_sales f 
left join gold.dim_customer c  
on c.customer_key = f.customer_key
group by 
c.country
order by sum(f.sales_amount) desc

